name: IACroper
main: dev.arubik.iacs.iacs
version: "%%__RESOURCE_VERSION__%%"
author: SodaDevs
api-version: 1.13
depend: [MythicLib]
softdepend:
  - "ItemsAdder"
soft-depend: [PlaceholderAPI]
description: "%%__USERNAME__%%"
commands:
      iacrop:
         description: general command